### ISSUE TITLE
[Meta] Thought collection of the pre V3.0.0 release review

### ISSUE THREAD

**Issue by SchoolGuy** [cobbler/koan#81]
This list should represent things we do want to possibly do for the next release V3.1.0:

- [ ] setup.py: `long_description` should be the `README.md` instead of a custom string
- [ ] init.py: We do want to have a main docstring for the Koan module - currently empty.
- [ ] app.py: Move CLI stuff into own module
- [ ] CLI: optparse --> argparse
- [ ] CLI: Add Version command
- [ ] License: Replace long text with SPDX text
- [ ] Obsolete scripts in bin/
- [ ] Docs: ovz-install
- [ ] Reasonable defaults instead of just none in `app.py`
- [ ] Check custom exceptions and maybe remove some of them
- [ ] Check and document optional dependencies
- [ ] Docs: Update and consolidate
- [ ] Code organization: Move `*-create.py` into submodule and shorten filenames
- [ ] Pacakging: maybe create subpackages to not install all virt types
- [ ] Check if register script is also available in Cobbler
- [ ] Check utils.py for obsolete stuff
- [ ] Tests: Raise coverage at least to 20%
- [ ] Packaging: native Debian
